# Generated by Django 4.0.6 on 2022-08-16 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_pokes_messages_likes_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, default=False, upload_to=user.models.uploadto)),
                ('content', models.TextField(max_length=2000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(max_length=555),
        ),
        migrations.CreateModel(
            name='PlogPostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('plogPost', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user.plogpost')),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_coments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
