# Generated by Django 4.0.6 on 2022-08-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_plogpost_alter_messages_message_plogpostcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plogpost',
            old_name='titel',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='plogpost',
            name='createdAt',
        ),
    ]
