# Generated by Django 4.0.6 on 2022-08-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_titel_plogpost_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plogpost',
            old_name='writer',
            new_name='user',
        ),
    ]
