# Generated by Django 4.0.6 on 2022-08-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_writer_plogpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.TextField(max_length=2255)),
            ],
        ),
    ]
