# Generated by Django 4.0.6 on 2022-08-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_bussinesstaff_bussinesmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifts', models.CharField(choices=[('MOR', 'morning'), ('EVE', 'evening')], default='MOR', max_length=255)),
                ('bussines', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bussinesShift', to='user.bussines')),
                ('staff', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bussinesStaff', to='user.bussinesstaff')),
            ],
        ),
    ]
