# Generated by Django 4.0.6 on 2022-08-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinesstaff',
            name='bussines',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='busness', to='user.bussines'),
        ),
    ]
