# Generated by Django 4.0.6 on 2022-08-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_bussinesstaff_bussines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinesstaff',
            name='staffId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
