# Generated by Django 4.0.6 on 2022-08-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_bussinesstaff_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shifts',
            field=models.CharField(choices=[('MOR', 'Morning'), ('EVE', 'Evening')], default='MOR', max_length=255),
        ),
        migrations.CreateModel(
            name='HoursCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('startAt', models.DateTimeField()),
                ('finishat', models.DateTimeField()),
                ('shift', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyShift', to='user.shift')),
                ('staff', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyHoursCard', to='user.bussinesstaff')),
            ],
        ),
    ]
