# Generated by Django 4.0.6 on 2022-08-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_shift_shifts_hourscard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourscard',
            old_name='finishat',
            new_name='finishAt',
        ),
    ]
