# Generated by Django 4.0.6 on 2022-08-21 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_finishat_hourscard_finishat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.DateTimeField(verbose_name=datetime.time(23, 40, 55, 979051)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.DateTimeField(verbose_name=datetime.time(23, 40, 55, 979051)),
        ),
    ]
