# Generated by Django 4.0.6 on 2022-08-21 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_hourscard_finishat_alter_hourscard_startat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourscard',
            name='day',
            field=models.DateField(default=datetime.date(2022, 8, 21)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.DateTimeField(default=datetime.time(23, 43, 40, 387534)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.DateTimeField(default=datetime.time(23, 43, 40, 387534)),
        ),
    ]
