# Generated by Django 4.0.6 on 2022-08-21 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_hourscard_day_alter_hourscard_finishat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.DateTimeField(default=datetime.time(23, 46, 6, 929255)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.DateTimeField(default=datetime.time(23, 46, 6, 929255)),
        ),
    ]
