# Generated by Django 4.0.6 on 2022-08-21 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_hourscard_finishat_alter_hourscard_startat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.TimeField(default=datetime.time(23, 48, 29, 438303)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.TimeField(default=datetime.time(23, 48, 29, 438303)),
        ),
    ]
