# Generated by Django 4.0.6 on 2022-08-23 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_hourscard_finishat_alter_hourscard_startat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinesstaff',
            name='job',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='day',
            field=models.DateField(default=datetime.date(2022, 8, 23)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.TimeField(default=datetime.time(20, 36, 35, 726056)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.TimeField(default=datetime.time(20, 36, 35, 726056)),
        ),
    ]
