# Generated by Django 4.0.6 on 2022-08-27 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_bussinesstaff_job_alter_hourscard_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourscard',
            name='day',
            field=models.DateField(default=datetime.date(2022, 8, 27)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 8, 27, 11, 2, 2, 625169)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.TimeField(default=datetime.datetime(2022, 8, 27, 11, 2, 2, 625169)),
        ),
    ]
