# Generated by Django 4.0.6 on 2022-08-28 13:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_hourscard_day_alter_hourscard_finishat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourscard',
            name='day',
            field=models.DateField(default=datetime.date(2022, 8, 28)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 8, 28, 16, 16, 56, 265615)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.TimeField(default=datetime.datetime(2022, 8, 28, 16, 16, 56, 265615)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
