# Generated by Django 4.0.6 on 2022-08-28 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_hourscard_day_alter_hourscard_finishat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 8, 28, 16, 23, 59, 890270)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.TimeField(default=datetime.datetime(2022, 8, 28, 16, 23, 59, 890270)),
        ),
    ]
