# Generated by Django 4.0.6 on 2022-08-28 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_hourscard_finishat_alter_hourscard_startat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 8, 28, 16, 27, 20, 744775)),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.TimeField(default=datetime.datetime(2022, 8, 28, 16, 27, 20, 744775)),
        ),
    ]
