# Generated by Django 4.0.6 on 2022-08-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_bussinesmanager_bussiness_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BussinesManager',
        ),
    ]
