# Generated by Django 4.0 on 2022-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_bussines_user_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourscard',
            name='finishAt',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='startAt',
            field=models.TextField(max_length=255),
        ),
    ]
