# Generated by Django 4.1 on 2022-09-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_bussines_bussinessid_alter_bussines_catogery_and_more'),
        ('user', '0033_alter_hourscard_finishat_alter_hourscard_startat'),
    ]

    operations = [
    ]
