# Generated by Django 4.0 on 2022-11-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_hourscard_finishat_alter_hourscard_startat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceType', models.TextField(max_length=255)),
                ('issueAt', models.DateField(default=True)),
                ('reciverName', models.DateField(max_length=255)),
                ('reciverId', models.DateField(max_length=255)),
                ('reciverEmail', models.DateField(max_length=255)),
                ('invoiceDetail', models.DateField(max_length=255)),
                ('invoiceAmount', models.DateField(max_length=255)),
                ('invoiceTax', models.DateField(default=True)),
                ('paymentTill', models.DateField(default=True)),
                ('bussiness', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bussiness', to='user.bussines')),
            ],
        ),
    ]
