# Generated by Django 4.0 on 2022-11-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoiceAmount',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoiceDetail',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoiceTax',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='reciverEmail',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='reciverId',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='reciverName',
            field=models.TextField(max_length=255),
        ),
    ]
