# Generated by Django 4.0 on 2022-11-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_invoices_invoiceamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoiceAmount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoiceTax',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoiceType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='reciverEmail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='reciverId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='reciverName',
            field=models.CharField(max_length=255),
        ),
    ]
