# Generated by Django 4.0 on 2022-11-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_bussines_bussinessid_alter_bussines_catogery_and_more'),
        ('user', '0036_alter_invoices_invoiceamount_and_more'),
    ]

    operations = [
    ]
