# Generated by Django 4.0 on 2022-11-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_merge_20221107_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paysleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startAt', models.DateField(default=True)),
                ('month', models.DateField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('visaId', models.CharField(max_length=255)),
                ('regularHours', models.CharField(max_length=255)),
                ('extraHours', models.CharField(blank=True, max_length=255)),
                ('weekendHours', models.CharField(blank=True, max_length=255)),
                ('transportations', models.CharField(blank=True, max_length=255)),
                ('hoursFee', models.CharField(max_length=255)),
                ('tax', models.CharField(max_length=255)),
                ('finalAmount', models.BooleanField(default=True)),
                ('bussiness', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Paysleevebussiness', to='user.bussines')),
            ],
        ),
    ]
