# Generated by Django 4.0 on 2022-11-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_paysleeve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysleeve',
            name='finalAmount',
            field=models.CharField(max_length=255),
        ),
    ]
