# Generated by Django 4.0 on 2022-11-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='bussiness',
        ),
        migrations.AddField(
            model_name='invoices',
            name='bussines',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='myInvoice', to='user.bussines'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='time',
            field=models.TimeField(default=True),
        ),
    ]
