# Generated by Django 4.0 on 2022-11-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_alter_invoices_bussines_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='invoiceAmount',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='invoiceDetail',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='invoiceTax',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='issueAt',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='paymentTill',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='reciverEmail',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='reciverId',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='reciverName',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
