# Generated by Django 4.0 on 2022-11-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_remove_invoices_invoiceamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employeeid', models.CharField(max_length=255)),
                ('bussines', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='KablaBusness', to='user.bussines')),
            ],
        ),
    ]
