# Generated by Django 4.0 on 2022-11-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_kabla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabla',
            name='bussines',
        ),
    ]
