# Generated by Django 4.0 on 2022-11-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_remove_kabla_bussines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kabla',
        ),
    ]
