# Generated by Django 4.1.3 on 2022-11-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_delete_kabla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
