# Generated by Django 4.1.3 on 2022-11-13 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_delete_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicetype', models.CharField(max_length=255)),
                ('issuedate', models.DateField(default=True)),
                ('creatername', models.CharField(max_length=255)),
                ('createrid', models.CharField(max_length=255)),
                ('recivername', models.CharField(max_length=255)),
                ('reciverId', models.CharField(max_length=255)),
                ('reciverEmail', models.CharField(max_length=255)),
                ('invoiceDetail', models.TextField(max_length=255)),
                ('invoiceAmount', models.CharField(max_length=255)),
                ('invoiceTax', models.BooleanField(default=True)),
                ('paymentTill', models.DateField(default=True)),
                ('bus', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user.bussines')),
            ],
        ),
    ]
