# Generated by Django 4.1.3 on 2022-11-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceAmount',
            new_name='invoiceamount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceDetail',
            new_name='invoicedetail',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceTax',
            new_name='invoicetax',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='paymentTill',
            new_name='paymentdate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='reciverEmail',
            new_name='reciveremail',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='reciverId',
            new_name='reciverid',
        ),
    ]
