# Generated by Django 4.1.3 on 2022-11-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_rename_invoiceamount_invoice_invoiceamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='paymentdate',
            new_name='expireddate',
        ),
    ]
